language: php

php:
  - 7.2
  - 7.3

sudo: false

env:
  matrix:
    - DB=mysql db_dsn='mysql://root@0.0.0.0/cakephp_test'

  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.3
      env: PHPCS=1 DEFAULT=0

    - php: 7.3
      env: PHPSTAN=1 DEFAULT=0

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 7.3 ]]; then phpenv config-rm xdebug.ini; fi

  - composer self-update
  - composer install --prefer-dist --no-interaction

  - if [[ $DB = 'mysql' ]]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi

  - if [[ $PHPCS = 1 ]]; then composer require cakephp/cakephp-codesniffer:"^3.0"; fi
  - if [[ $PHPSTAN = 1 ]]; then composer require phpstan/phpstan; fi

script:
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.3 ]]; then vendor/bin/phpunit; fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.3 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi

  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi
  - if [[ $PHPSTAN = 1 ]]; then vendor/bin/phpstan analyse -c phpstan.neon -l 7 src; fi

after_success:
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.3 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
