language: php

services:
  - mysql

php:
  - 7.2
  - 7.3
  - 7.4

sudo: false

env:
  matrix:
    - DB=mysql db_user=root db_host=0.0.0.0 db_name=cakephp_test

  global:
    - DEFAULT=1 PREFER_LOWEST="--prefer-lowest"

matrix:
  fast_finish: true

  include:
    - php: 7.4
      env: PREFER_LOWEST="" DB=mysql db_user=root db_host=0.0.0.0 db_name=cakephp_test

    - php: 7.4
      env: PHPCS=1 DEFAULT=0 PREFER_LOWEST=""

    - php: 7.4
      env: PHPSTAN=1 DEFAULT=0 PREFER_LOWEST=""

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer update --prefer-stable --prefer-dist --no-interaction $PREFER_LOWEST

  - if [[ $DB = 'mysql' ]]; then mysql -e 'CREATE DATABASE cakephp_test; GRANT ALL PRIVILEGES ON cakephp_test.* TO travis@localhost;'; fi

  - if [[ $PHPCS = 1 ]]; then composer require cakephp/cakephp-codesniffer:"^3.0"; fi
  - if [[ $PHPSTAN = 1 ]]; then composer require phpstan/phpstan; fi

script:
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.4 ]]; then vendor/bin/phpunit; fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.4 ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml; fi

  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi
  - if [[ $PHPSTAN = 1 ]]; then vendor/bin/phpstan analyse -c phpstan.neon -l 7 src; fi

after_success:
  - |
    if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.4 ]]; then
      curl -s https://codecov.io/bash > codecov
      sed -i -e 's/TRAVIS_.*_VERSION/^TRAVIS_.*_VERSION=/' codecov
      bash codecov
    fi

notifications:
  email: false
