name: CI

on:
  push:
    branches:
      - master
      - 3.next
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  testsuite:
    uses: cakephp/.github/.github/workflows/testsuite-with-db.yml@5.x
    secrets: inherit
    strategy:
      matrix:
        db-type: [mysql]

  cs-stan:
    uses: cakephp/.github/.github/workflows/cs-stan.yml@5.x
    secrets: inherit
